export type Exercise = {
  id: string;
  subject: string;
  topic: string;
  difficulty: string;
  questionType: 'QCM' | 'CALCUL';
  question: string;
  options: string | null;
  correctAnswer: string;
  solution: string;
  points: number;
};

export const subjects = [
  'MATHEMATIQUES',
  'PHYSIQUE',
  'CHIMIE',
  'OPTIQUE',
  'CULTURE_GENERALE',
] as const;

export const exercises: Exercise[] = [
  // ===================== MATHEMATIQUES (9) =====================
  // --- Algèbre ---
  {
    id: 'ex_1',
    subject: 'MATHEMATIQUES',
    topic: 'Algèbre',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Si f(x) = x² - 4x + 3, quelles sont les racines de f(x) = 0 ?',
    options: JSON.stringify(['x = 1 et x = 3', 'x = -1 et x = -3', 'x = 2 et x = 6', 'x = -2 et x = 2']),
    correctAnswer: 'x = 1 et x = 3',
    solution: 'x² - 4x + 3 = 0\nOn utilise le discriminant : Δ = b² - 4ac = (-4)² - 4(1)(3) = 16 - 12 = 4\nΔ > 0, donc deux racines :\nx₁ = (4 - √4) / 2 = (4 - 2) / 2 = 1\nx₂ = (4 + √4) / 2 = (4 + 2) / 2 = 3\n\nLes racines sont x = 1 et x = 3.',
    points: 4,
  },
  // --- Géométrie ---
  {
    id: 'ex_2',
    subject: 'MATHEMATIQUES',
    topic: 'Géométrie',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Quelle est l'aire d'un triangle de base 10 cm et de hauteur 6 cm ?",
    options: JSON.stringify(['60 cm²', '30 cm²', '16 cm²', '36 cm²']),
    correctAnswer: '30 cm²',
    solution: "Aire du triangle = (base × hauteur) / 2\n= (10 × 6) / 2\n= 60 / 2\n= 30 cm²",
    points: 4,
  },
  // --- Géométrie analytique ---
  {
    id: 'ex_3',
    subject: 'MATHEMATIQUES',
    topic: 'Géométrie analytique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Quelle est l'équation cartésienne de la droite passant par A(2, 3) et B(-1, 0) ?",
    options: JSON.stringify(['y = x + 1', 'y = -x + 5', 'y = x - 1', 'y = -x - 1']),
    correctAnswer: 'y = x + 1',
    solution: 'Pente : m = (0 - 3) / (-1 - 2) = -3 / -3 = 1\nÉquation : y - y_A = m(x - x_A)\ny - 3 = 1(x - 2)\ny = x + 1',
    points: 4,
  },
  // --- Trigonométrie ---
  {
    id: 'ex_4',
    subject: 'MATHEMATIQUES',
    topic: 'Trigonométrie',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Dans un triangle rectangle, si l'angle θ = 30° et l'hypoténuse = 10, que vaut le côté adjacent ?",
    options: JSON.stringify(['5√3', '5', '10√3', '10']),
    correctAnswer: '5√3',
    solution: "cos(30°) = adjacent / hypoténuse\ncos(30°) = √3/2\n\nadjacent = hypoténuse × cos(30°)\n= 10 × (√3/2)\n= 5√3",
    points: 4,
  },
  // --- Analyse ---
  {
    id: 'ex_5',
    subject: 'MATHEMATIQUES',
    topic: 'Analyse',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la dérivée de f(x) = 3x⁴ - 2x² + 5x - 1 ?',
    options: JSON.stringify(['12x³ - 4x + 5', '12x³ - 2x + 5', '3x³ - 4x + 5', '12x⁴ - 4x + 5']),
    correctAnswer: '12x³ - 4x + 5',
    solution: "f(x) = 3x⁴ - 2x² + 5x - 1\nf'(x) = 4 × 3x³ - 2 × 2x + 5 - 0\n= 12x³ - 4x + 5",
    points: 4,
  },
  // --- Limites ---
  {
    id: 'ex_6',
    subject: 'MATHEMATIQUES',
    topic: 'Limites',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Calculez la limite de (sin(3x)) / x lorsque x tend vers 0. Donnez la valeur numérique.',
    options: null,
    correctAnswer: '3',
    solution: 'On sait que lim(sin(x)/x) = 1 quand x → 0.\nlim(sin(3x)/x) = 3 × lim(sin(3x)/(3x)) = 3 × 1 = 3',
    points: 4,
  },
  // --- Probabilités ---
  {
    id: 'ex_7',
    subject: 'MATHEMATIQUES',
    topic: 'Probabilités',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "On lance un dé à 6 faces. Quelle est la probabilité d'obtenir un nombre pair ?",
    options: JSON.stringify(['1/2', '1/3', '1/6', '2/3']),
    correctAnswer: '1/2',
    solution: 'Nombres pairs sur un dé : {2, 4, 6} → 3 résultats favorables\nNombre total de résultats possibles : 6\n\nP(pair) = 3/6 = 1/2',
    points: 4,
  },
  // --- Suites numériques ---
  {
    id: 'ex_8',
    subject: 'MATHEMATIQUES',
    topic: 'Suites numériques',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Soit la suite géométrique (v_n) de premier terme v_1 = 2 et de raison q = 3. Calculez la somme des 5 premiers termes S_5.',
    options: null,
    correctAnswer: '242',
    solution: 'S_n = v_1 × (q^n - 1) / (q - 1)\nS_5 = 2 × (3^5 - 1) / (3 - 1)\nS_5 = 2 × (243 - 1) / 2\nS_5 = 2 × 242 / 2\nS_5 = 242',
    points: 4,
  },
  // --- Nombres complexes ---
  {
    id: 'ex_9',
    subject: 'MATHEMATIQUES',
    topic: 'Nombres complexes',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Soit z1 = 1 + i et z2 = 2 - i. Calculez le module du produit z1 × z2.',
    options: null,
    correctAnswer: '√10',
    solution: 'Propriété : |z1 × z2| = |z1| × |z2|\n|z1| = √(1² + 1²) = √2\n|z2| = √(2² + (-1)²) = √5\n|z1 × z2| = √2 × √5 = √10',
    points: 4,
  },

  // ===================== PHYSIQUE (9) =====================
  // --- Mécanique ---
  {
    id: 'ex_10',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Un objet de masse 5 kg est soumis à une force de 20 N. Quelle est son accélération ?',
    options: JSON.stringify(['4 m/s²', '100 m/s²', '0.25 m/s²', '15 m/s²']),
    correctAnswer: '4 m/s²',
    solution: 'Deuxième loi de Newton : F = ma\nDonc : a = F/m\na = 20 N / 5 kg\na = 4 m/s²',
    points: 4,
  },
  {
    id: 'ex_11',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Une balle est lancée verticalement vers le haut avec une vitesse initiale de 20 m/s. Quelle hauteur maximale atteint-elle ? (g = 10 m/s²)',
    options: JSON.stringify(['20 m', '10 m', '40 m', '200 m']),
    correctAnswer: '20 m',
    solution: 'Au point le plus haut, la vitesse finale v = 0.\nv² = v₀² - 2gh\n0 = (20)² - 2(10)h\n20h = 400\nh = 20 m',
    points: 4,
  },
  {
    id: 'ex_12',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Un bloc de 2 kg glisse sur un plan incliné à 30° sans frottement. Quelle est l'accélération du bloc en m/s² ? (g = 10 m/s²). Donnez la valeur numérique uniquement.",
    options: null,
    correctAnswer: '5',
    solution: 'F = mg sin(θ) = 2 × 10 × sin(30°) = 20 × 0.5 = 10 N\na = F/m = 10/2 = 5 m/s²',
    points: 4,
  },
  // --- Électricité ---
  {
    id: 'ex_13',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Dans un circuit, une résistance de 10 Ω est traversée par un courant de 2 A. Quelle est la tension à ses bornes ?',
    options: JSON.stringify(['20 V', '5 V', '0.2 V', '12 V']),
    correctAnswer: '20 V',
    solution: "Loi d'Ohm : U = RI\nU = 10 Ω × 2 A\nU = 20 V",
    points: 4,
  },
  {
    id: 'ex_14',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Trois résistances de 6 Ω chacune sont montées en parallèle. Quelle est la résistance équivalente ?",
    options: JSON.stringify(['2 Ω', '18 Ω', '6 Ω', '3 Ω']),
    correctAnswer: '2 Ω',
    solution: '1/R_eq = 1/R₁ + 1/R₂ + 1/R₃\n1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2\nR_eq = 2 Ω',
    points: 4,
  },
  {
    id: 'ex_15',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Un générateur de force électromotrice E = 12 V et de résistance interne r = 1 Ω alimente une résistance R = 5 Ω. Calculez l'intensité du courant en ampères.",
    options: null,
    correctAnswer: '2',
    solution: "Loi de Pouillet : I = E / (R + r)\nI = 12 / (5 + 1)\nI = 12 / 6\nI = 2 A",
    points: 4,
  },
  // --- Thermodynamique ---
  {
    id: 'ex_16',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Combien de joules faut-il pour élever la température de 200 g d'eau de 20°C à 70°C ? (c = 4,18 J/g·°C)",
    options: JSON.stringify(['41 800 J', '20 900 J', '4 180 J', '83 600 J']),
    correctAnswer: '41 800 J',
    solution: 'Q = mcΔT\nQ = 200 × 4,18 × (70 - 20)\nQ = 200 × 4,18 × 50\nQ = 41 800 J',
    points: 4,
  },
  {
    id: 'ex_17',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Un gaz parfait à 300 K occupe un volume de 2 L sous une pression de 1 atm. Quel volume occupe-t-il à 600 K sous la même pression ?",
    options: JSON.stringify(['4 L', '2 L', '1 L', '8 L']),
    correctAnswer: '4 L',
    solution: 'Loi de Charles (P constante) : V₁/T₁ = V₂/T₂\nV₂ = V₁ × T₂/T₁\nV₂ = 2 × 600/300\nV₂ = 2 × 2 = 4 L',
    points: 4,
  },
  {
    id: 'ex_18',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Un moteur de Carnot fonctionne entre une source chaude à 500 K et une source froide à 300 K. Calculez son rendement en pourcentage (valeur numérique uniquement, sans le symbole %).",
    options: null,
    correctAnswer: '40',
    solution: 'Rendement d\'un cycle de Carnot : η = 1 - T_froide / T_chaude\nη = 1 - 300/500\nη = 1 - 0,6\nη = 0,4 soit 40 %\n\nLe rendement maximal d\'un moteur thermique ne dépend que des températures des deux sources.',
    points: 4,
  },

  // ===================== CHIMIE (9) =====================
  // --- Atomistique ---
  {
    id: 'ex_19',
    subject: 'CHIMIE',
    topic: 'Atomistique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quel est le nombre de neutrons dans un atome de carbone ¹⁴C (Z=6) ?',
    options: JSON.stringify(['8', '6', '14', '20']),
    correctAnswer: '8',
    solution: 'Nombre de neutrons = A - Z\nA = nombre de masse = 14\nZ = numéro atomique = 6\nN = 14 - 6 = 8 neutrons',
    points: 4,
  },
  {
    id: 'ex_20',
    subject: 'CHIMIE',
    topic: 'Atomistique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la configuration électronique du potassium (K, Z=19) dans son état fondamental ?',
    options: JSON.stringify([
      '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
      '1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹',
      '1s² 2s² 2p⁶ 3s² 3p⁷',
      '1s² 2s² 2p⁶ 3s² 3p⁶ 4s²',
    ]),
    correctAnswer: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
    solution: "Le potassium a 19 électrons.\n1s² (2) → 2s² (4) → 2p⁶ (10) → 3s² (12) → 3p⁶ (18) → 4s¹ (19)\nNote : 4s se remplit avant 3d car 4s a une énergie plus basse.",
    points: 4,
  },
  // --- Chimie organique ---
  {
    id: 'ex_21',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Quel est le nom de l'alcane ayant la formule C₃H₈ ?",
    options: JSON.stringify(['Propane', 'Méthane', 'Éthane', 'Butane']),
    correctAnswer: 'Propane',
    solution: "Formule générale des alcanes : CₙH₂ₙ₊₂\nPour C₃H₈ : n = 3\nPréfixe pour 3 carbones : \"prop\" → Propane",
    points: 4,
  },
  {
    id: 'ex_22',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la fonction organique caractérisée par le groupe -CHO ?',
    options: JSON.stringify(['Aldéhyde', 'Acide carboxylique', 'Alcool', 'Cétone']),
    correctAnswer: 'Aldéhyde',
    solution: "Le groupe -CHO est le groupe fonctionnel des aldéhydes.\n- -OH : Alcool\n- -CHO : Aldéhyde\n- -CO- : Cétone\n- -COOH : Acide carboxylique",
    points: 4,
  },
  // --- Solutions ---
  {
    id: 'ex_23',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "On dissout 10 g de NaCl dans 500 mL d'eau. Quelle est la concentration massique en g/L ?",
    options: JSON.stringify(['20 g/L', '10 g/L', '0.02 g/L', '50 g/L']),
    correctAnswer: '20 g/L',
    solution: 'Cm = m / V\nm = 10 g\nV = 500 mL = 0.5 L\nCm = 10 / 0.5 = 20 g/L',
    points: 4,
  },
  {
    id: 'ex_24',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "On prépare 250 mL d'une solution de HCl à 0.5 mol/L à partir d'une solution mère à 2 mol/L. Quel volume en mL de solution mère faut-il prélever ?",
    options: null,
    correctAnswer: '62.5',
    solution: 'Dilution : C₁V₁ = C₂V₂\nV₁ = C₂V₂ / C₁ = (0.5 × 250) / 2 = 125 / 2 = 62.5 mL',
    points: 4,
  },
  // --- Réactions chimiques ---
  {
    id: 'ex_25',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Quelle est l'équation bilan équilibrée de la combustion du méthane CH₄ ?",
    options: JSON.stringify([
      'CH₄ + 2O₂ → CO₂ + 2H₂O',
      'CH₄ + O₂ → CO₂ + H₂O',
      '2CH₄ + 4O₂ → 2CO₂ + 4H₂O',
      'CH₄ + 2O₂ → CO + 2H₂O',
    ]),
    correctAnswer: 'CH₄ + 2O₂ → CO₂ + 2H₂O',
    solution: 'CH₄ + O₂ → CO₂ + H₂O\nC : 1 → 1 (ok)\nH : 4 → 2×2 = 4 (ok)\nO : 2×2 = 4 → 2+2 = 4 (ok)\nÉquation : CH₄ + 2O₂ → CO₂ + 2H₂O',
    points: 4,
  },
  {
    id: 'ex_26',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Selon l'équation N₂ + 3H₂ → 2NH₃, combien de grammes de NH₃ peuvent être produits à partir de 14 g de N₂ ? (N=14, H=1). Donnez la valeur en grammes.",
    options: null,
    correctAnswer: '17',
    solution: 'M(N₂) = 2×14 = 28 g/mol\nn(N₂) = 14/28 = 0.5 mol\n1 mol N₂ → 2 mol NH₃\n0.5 mol N₂ → 1 mol NH₃\nM(NH₃) = 14 + 3×1 = 17 g/mol\nm(NH₃) = 1 × 17 = 17 g',
    points: 4,
  },
  {
    id: 'ex_27',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Dans la réaction d'oxydoréduction : Cu²⁺ + Zn → Cu + Zn²⁺, quel est l'oxydant ?",
    options: JSON.stringify(['Cu²⁺', 'Zn', 'Cu', 'Zn²⁺']),
    correctAnswer: 'Cu²⁺',
    solution: "L'oxydant est l'espèce qui se réduit (qui gagne des électrons).\n\nDemi-réaction de réduction : Cu²⁺ + 2e⁻ → Cu\nDemi-réaction d'oxydation : Zn → Zn²⁺ + 2e⁻\n\nCu²⁺ est l'oxydant (il se réduit), Zn est le réducteur (il s'oxyde).",
    points: 4,
  },

  // ===================== OPTIQUE (9) =====================
  // --- Réflexion ---
  {
    id: 'ex_28',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Un rayon lumineux frappe un miroir plan avec un angle d'incidence de 40°. Quel est l'angle de réflexion ?",
    options: JSON.stringify(['40°', '50°', '80°', '20°']),
    correctAnswer: '40°',
    solution: "Première loi de la réflexion : l'angle de réflexion est toujours égal à l'angle d'incidence = 40°",
    points: 4,
  },
  {
    id: 'ex_29',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Un objet de 5 cm est placé à 10 cm d'un miroir concave de distance focale 5 cm. Quelle est la taille de l'image ?",
    options: JSON.stringify(['5 cm (image réelle inversée)', '5 cm (image virtuelle droite)', '10 cm (image réelle inversée)', '2.5 cm (image virtuelle droite)']),
    correctAnswer: '5 cm (image réelle inversée)',
    solution: '1/f = 1/p + 1/q → 1/5 = 1/10 + 1/q → q = 10 cm\nγ = -q/p = -10/10 = -1\n|image| = 1 × 5 = 5 cm, inversée.',
    points: 4,
  },
  {
    id: 'ex_30',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Deux miroirs plans forment un angle de 60°. Un rayon lumineux subit deux réflexions successives sur ces miroirs. Quel est l'angle total de déviation du rayon en degrés ?",
    options: null,
    correctAnswer: '240',
    solution: "Pour deux miroirs plans formant un angle α, la déviation totale après deux réflexions est indépendante de l'angle d'incidence :\n\nδ = 360° - 2α\nδ = 360° - 2 × 60°\nδ = 360° - 120°\nδ = 240°",
    points: 4,
  },
  // --- Réfraction ---
  {
    id: 'ex_31',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Un rayon passe de l'air (n=1) vers l'eau (n=1.33) avec un angle d'incidence de 30°. Que se passe-t-il ?",
    options: JSON.stringify([
      'Le rayon se rapproche de la normale',
      "Le rayon s'éloigne de la normale",
      'Le rayon est totalement réfléchi',
      'Le rayon ne change pas de direction',
    ]),
    correctAnswer: 'Le rayon se rapproche de la normale',
    solution: 'n₁ sin(i) = n₂ sin(r)\n1 × sin(30°) = 1.33 × sin(r)\nsin(r) = 0.5 / 1.33 ≈ 0.376\nr ≈ 22° < i : le rayon se rapproche de la normale.',
    points: 4,
  },
  {
    id: 'ex_32',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: "Un rayon lumineux passe du verre (n=1.5) vers l'eau (n=1.33) avec un angle d'incidence de 30°. Calculez l'angle de réfraction en degrés (arrondi à l'entier le plus proche).",
    options: null,
    correctAnswer: '34',
    solution: "Loi de Snell-Descartes : n₁ sin(i) = n₂ sin(r)\n1,5 × sin(30°) = 1,33 × sin(r)\n1,5 × 0,5 = 1,33 × sin(r)\n0,75 = 1,33 × sin(r)\nsin(r) = 0,75 / 1,33 ≈ 0,5639\nr = arcsin(0,5639) ≈ 34,3° ≈ 34°",
    points: 4,
  },
  {
    id: 'ex_33',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: "Calculez l'angle critique pour la réflexion totale entre le verre (n=1.5) et l'air (n=1). Donnez la valeur en degrés (arrondie à l'entier le plus proche).",
    options: null,
    correctAnswer: '42',
    solution: 'n₁ sin(θc) = n₂ sin(90°)\n1.5 × sin(θc) = 1\nsin(θc) = 1/1.5 = 0.667\nθc = arcsin(0.667) ≈ 41.8° ≈ 42°',
    points: 4,
  },
  // --- Lentilles ---
  {
    id: 'ex_34',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Une lentille convergente est caractérisée par :',
    options: JSON.stringify([
      'Une distance focale positive',
      'Une distance focale négative',
      'Un foyer virtuel',
      'Une vergence négative',
    ]),
    correctAnswer: 'Une distance focale positive',
    solution: "Une lentille convergente a une distance focale f > 0 et une vergence C = 1/f > 0.\nElle fait converger les rayons vers un foyer réel.\n\n- Lentille convergente : f > 0, C > 0\n- Lentille divergente : f < 0, C < 0",
    points: 4,
  },
  {
    id: 'ex_35',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Une lentille convergente a une distance focale de 20 cm. Où se forme l'image d'un objet placé à 60 cm de la lentille ?",
    options: JSON.stringify(['30 cm de la lentille', '60 cm de la lentille', '20 cm de la lentille', '15 cm de la lentille']),
    correctAnswer: '30 cm de la lentille',
    solution: '1/f = 1/p + 1/q\n1/20 = 1/60 + 1/q\n1/q = 1/20 - 1/60 = 2/60 = 1/30\nq = 30 cm (image réelle).',
    points: 4,
  },
  {
    id: 'ex_36',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Deux lentilles convergentes de distances focales f₁ = 10 cm et f₂ = 20 cm sont accolées. Quelle est la vergence totale en dioptries ?',
    options: null,
    correctAnswer: '15',
    solution: 'C = C₁ + C₂ = 1/f₁ + 1/f₂\nC = 1/0.10 + 1/0.20 = 10 + 5 = 15 dioptries',
    points: 4,
  },

  // ===================== CULTURE GENERALE (9) =====================
  // --- Histoire d'Haïti ---
  {
    id: 'ex_37',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'En quelle année Haïti a-t-elle proclamé son indépendance ?',
    options: JSON.stringify(['1804', '1791', '1802', '1815']),
    correctAnswer: '1804',
    solution: "Haïti a proclamé son indépendance le 1er janvier 1804, sous la direction de Jean-Jacques Dessalines.",
    points: 4,
  },
  {
    id: 'ex_38',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Quel est le nom du dirigeant français qui a envoyé l'expédition pour reprendre Haïti en 1802 ?",
    options: JSON.stringify(['Napoléon Bonaparte', 'Louis XVI', 'Charles de Gaulle', 'Jacques Chirac']),
    correctAnswer: 'Napoléon Bonaparte',
    solution: "Napoléon Bonaparte a envoyé le général Charles Leclerc à la tête d'une expédition de plus de 20 000 soldats en 1802.",
    points: 4,
  },
  {
    id: 'ex_39',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'La Citadelle Laferrière a été construite sous le règne de quel empereur haïtien ?',
    options: JSON.stringify(['Henri Christophe', 'Jean-Jacques Dessalines', 'Faustin Soulouque', 'Alexandre Pétion']),
    correctAnswer: 'Henri Christophe',
    solution: "La Citadelle Laferrière a été construite entre 1805 et 1820 sous le règne du roi Henri Christophe. Classée au patrimoine mondial de l'UNESCO depuis 1982.",
    points: 4,
  },
  {
    id: 'ex_40',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel événement a marqué le début de la Révolution haïtienne en 1791 ?',
    options: JSON.stringify([
      'La cérémonie du Bois Caïman',
      'La prise de la Bastille',
      'Le serment de Pétion',
      'La bataille de Vertières',
    ]),
    correctAnswer: 'La cérémonie du Bois Caïman',
    solution: "La cérémonie du Bois Caïman, en août 1791, est considérée comme l'événement déclencheur de la Révolution haïtienne.",
    points: 4,
  },
  // --- Géographie ---
  {
    id: 'ex_41',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Quelle est la capitale d'Haïti ?",
    options: JSON.stringify(['Port-au-Prince', 'Cap-Haïtien', 'Les Cayes', 'Jérémie']),
    correctAnswer: 'Port-au-Prince',
    solution: "Port-au-Prince est la capitale et la plus grande ville d'Haïti, fondée en 1749.",
    points: 4,
  },
  {
    id: 'ex_42',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Quel est le plus haut sommet d'Haïti ?",
    options: JSON.stringify(['Pic la Selle', 'Pic Macaya', 'Montagne Noire', 'Morne de la Selle']),
    correctAnswer: 'Pic la Selle',
    solution: "Le Pic la Selle, dans le massif de la Selle, est le point culminant d'Haïti avec 2 680 mètres.",
    points: 4,
  },
  // --- Culture générale ---
  {
    id: 'ex_43',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: "Quelles sont les deux langues officielles d'Haïti ?",
    options: JSON.stringify(["Le français et le créole haïtien", "L'espagnol et le français", "L'anglais et le créole", "Le français et l'anglais"]),
    correctAnswer: 'Le français et le créole haïtien',
    solution: "Haïti a deux langues officielles : le français et le créole haïtien (kreyòl ayisyen).",
    points: 4,
  },
  {
    id: 'ex_44',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: "Quel organisme international Haïti a-t-elle rejoint en 1945, année de sa fondation ?",
    options: JSON.stringify(["L'ONU", "L'Union européenne", "L'OTAN", "L'UNESCO"]),
    correctAnswer: "L'ONU",
    solution: "Haïti est l'un des pays fondateurs de l'Organisation des Nations Unies (ONU), qu'elle a rejointe en 1945.",
    points: 4,
  },
  {
    id: 'ex_45',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel auteur haïtien est célèbre pour son roman "Gouverneurs de la rosée" ?',
    options: JSON.stringify(['Jacques Roumain', 'René Depestre', 'Jean Price-Mars', 'Frankétienne']),
    correctAnswer: 'Jacques Roumain',
    solution: 'Jacques Roumain (1907-1944) est l\'auteur de "Gouverneurs de la rosée" (1944), chef-d\'oeuvre de la littérature caribéenne.',
    points: 4,
  },

  // ===================== ADDITIONAL MATHEMATIQUES (15) =====================
  {
    id: 'ex_46',
    subject: 'MATHEMATIQUES',
    topic: 'Algèbre',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quel est le résultat de (2x + 3)(x - 1) ?',
    options: JSON.stringify(['2x² + x - 3', '2x² - x + 3', '2x² + x + 3', '2x² - 2x - 3']),
    correctAnswer: '2x² + x - 3',
    solution: '(2x + 3)(x - 1) = 2x(x) + 2x(-1) + 3(x) + 3(-1)\n= 2x² - 2x + 3x - 3\n= 2x² + x - 3',
    points: 4,
  },
  {
    id: 'ex_47',
    subject: 'MATHEMATIQUES',
    topic: 'Analyse',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quelle est la primitive de f(x) = 6x² ?',
    options: JSON.stringify(['2x³ + C', '3x³ + C', '6x³ + C', 'x³ + C']),
    correctAnswer: '2x³ + C',
    solution: 'F(x) = ∫ 6x² dx = 6 × (x³/3) + C = 2x³ + C',
    points: 4,
  },
  {
    id: 'ex_48',
    subject: 'MATHEMATIQUES',
    topic: 'Analyse',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la dérivée de f(x) = ln(3x + 1) ?',
    options: JSON.stringify(['3/(3x + 1)', '1/(3x + 1)', '3ln(3x + 1)', '1/(3x + 1)²']),
    correctAnswer: '3/(3x + 1)',
    solution: 'f(x) = ln(u) avec u = 3x + 1\nf\'(x) = u\'/u = 3/(3x + 1)',
    points: 4,
  },
  {
    id: 'ex_49',
    subject: 'MATHEMATIQUES',
    topic: 'Analyse',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Calculez l\'intégrale de 0 à 2 de (3x² + 1) dx. Donnez la valeur exacte.',
    options: null,
    correctAnswer: '10',
    solution: '∫₀² (3x² + 1) dx = [x³ + x]₀² = (8 + 2) - (0 + 0) = 10',
    points: 4,
  },
  {
    id: 'ex_50',
    subject: 'MATHEMATIQUES',
    topic: 'Géométrie',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel est le volume d\'un cône de rayon 3 cm et de hauteur 8 cm ?',
    options: JSON.stringify(['24π cm³', '72π cm³', '12π cm³', '36π cm³']),
    correctAnswer: '24π cm³',
    solution: 'V = (1/3)πr²h = (1/3) × π × 9 × 8 = 24π cm³',
    points: 4,
  },
  {
    id: 'ex_51',
    subject: 'MATHEMATIQUES',
    topic: 'Trigonométrie',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la valeur de tan(45°) + sin(30°) ?',
    options: JSON.stringify(['1.5', '1', '2', '0.5']),
    correctAnswer: '1.5',
    solution: 'tan(45°) = 1 et sin(30°) = 0.5\ntan(45°) + sin(30°) = 1 + 0.5 = 1.5',
    points: 4,
  },
  {
    id: 'ex_52',
    subject: 'MATHEMATIQUES',
    topic: 'Trigonométrie',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quelle est la valeur de cos(2α) si cos(α) = 3/5 ?',
    options: JSON.stringify(['-7/25', '7/25', '24/25', '-24/25']),
    correctAnswer: '-7/25',
    solution: 'cos(2α) = 2cos²(α) - 1\ncos(2α) = 2(9/25) - 1 = 18/25 - 1 = -7/25',
    points: 4,
  },
  {
    id: 'ex_53',
    subject: 'MATHEMATIQUES',
    topic: 'Nombres complexes',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Soit z = 3 + 4i. Quel est le module de z ?',
    options: JSON.stringify(['5', '7', '√7', '25']),
    correctAnswer: '5',
    solution: '|z| = √(3² + 4²) = √(9 + 16) = √25 = 5',
    points: 4,
  },
  {
    id: 'ex_54',
    subject: 'MATHEMATIQUES',
    topic: 'Nombres complexes',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Soit z = 1 + i√3. Calculez l\'argument principal de z en degrés.',
    options: null,
    correctAnswer: '60',
    solution: 'z = 1 + i√3\n|z| = √(1 + 3) = 2\narg(z) = arctan(√3/1) = 60°',
    points: 4,
  },
  {
    id: 'ex_55',
    subject: 'MATHEMATIQUES',
    topic: 'Probabilités',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'On tire 2 cartes d\'un jeu de 32 cartes. Quelle est la probabilité d\'obtenir 2 as ?',
    options: JSON.stringify(['1/248', '1/16', '1/8', '1/32']),
    correctAnswer: '1/248',
    solution: 'Nombre de façons de tirer 2 cartes : C(32,2) = 496\nNombre de façons de tirer 2 as : C(4,2) = 6\nP = 6/496 = 1/248',
    points: 4,
  },
  {
    id: 'ex_56',
    subject: 'MATHEMATIQUES',
    topic: 'Probabilités',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Dans une classe de 30 élèves, 18 aiment les maths et 15 aiment la physique. Si 8 aiment les deux, combien n\'aiment ni l\'un ni l\'autre ?',
    options: JSON.stringify(['5', '7', '3', '10']),
    correctAnswer: '5',
    solution: 'Formule d\'inclusion-exclusion : |M ∪ P| = |M| + |P| - |M ∩ P| = 18 + 15 - 8 = 25\nÉlèves n\'aimant ni l\'un ni l\'autre : 30 - 25 = 5',
    points: 4,
  },
  {
    id: 'ex_57',
    subject: 'MATHEMATIQUES',
    topic: 'Suites numériques',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Soit la suite arithmétique de premier terme u₁ = 5 et de raison r = 3. Que vaut u₁₀ ?',
    options: JSON.stringify(['32', '30', '35', '27']),
    correctAnswer: '32',
    solution: 'u_n = u₁ + (n-1)r\nu₁₀ = 5 + 9 × 3 = 5 + 27 = 32',
    points: 4,
  },
  {
    id: 'ex_58',
    subject: 'MATHEMATIQUES',
    topic: 'Suites numériques',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Soit la suite arithmétique de premier terme 3 et de raison 4. Calculez la somme des 10 premiers termes S₁₀.',
    options: null,
    correctAnswer: '210',
    solution: 'u₁ = 3, r = 4\nu₁₀ = 3 + 9 × 4 = 39\nS₁₀ = 10 × (u₁ + u₁₀) / 2 = 10 × (3 + 39) / 2 = 10 × 21 = 210',
    points: 4,
  },
  {
    id: 'ex_59',
    subject: 'MATHEMATIQUES',
    topic: 'Limites',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la limite de (x² - 9)/(x - 3) lorsque x tend vers 3 ?',
    options: JSON.stringify(['6', '3', '9', '0']),
    correctAnswer: '6',
    solution: '(x² - 9)/(x - 3) = (x - 3)(x + 3)/(x - 3) = x + 3 pour x ≠ 3\nlim = 3 + 3 = 6',
    points: 4,
  },
  {
    id: 'ex_60',
    subject: 'MATHEMATIQUES',
    topic: 'Géométrie analytique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Calculez la distance entre les points A(1, 2) et B(4, 6). Donnez la valeur exacte.',
    options: null,
    correctAnswer: '5',
    solution: 'd = √((4-1)² + (6-2)²) = √(9 + 16) = √25 = 5',
    points: 4,
  },

  // ===================== ADDITIONAL PHYSIQUE (15) =====================
  {
    id: 'ex_61',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Un objet parcourt 100 m en 10 s avec une vitesse constante. Quelle est sa vitesse ?',
    options: JSON.stringify(['10 m/s', '100 m/s', '1000 m/s', '1 m/s']),
    correctAnswer: '10 m/s',
    solution: 'v = d/t = 100/10 = 10 m/s',
    points: 4,
  },
  {
    id: 'ex_62',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Un satellite tourne autour de la Terre à une altitude où g = 4 m/s². Si sa masse est 500 kg, quel est son poids ?',
    options: JSON.stringify(['2000 N', '5000 N', '500 N', '200 N']),
    correctAnswer: '2000 N',
    solution: 'P = mg = 500 × 4 = 2000 N\nLe poids dépend de la gravité locale, pas seulement de la masse.',
    points: 4,
  },
  {
    id: 'ex_63',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Un corps de masse 3 kg est lancé horizontalement à 8 m/s depuis une hauteur de 20 m. Calculez le temps de chute en secondes. (g = 10 m/s², valeur arrondie à 2 décimales).',
    options: null,
    correctAnswer: '2',
    solution: 'h = ½gt²\n20 = ½ × 10 × t²\nt² = 4\nt = 2 s',
    points: 4,
  },
  {
    id: 'ex_64',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Un circuit série comporte une résistance R₁ = 4 Ω et R₂ = 6 Ω alimentés sous 10 V. Quelle est l\'intensité du courant ?',
    options: JSON.stringify(['1 A', '2 A', '0.5 A', '10 A']),
    correctAnswer: '1 A',
    solution: 'Réq = R₁ + R₂ = 4 + 6 = 10 Ω\nI = U/R = 10/10 = 1 A',
    points: 4,
  },
  {
    id: 'ex_65',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Un condensateur de capacité C = 100 µF est chargé sous une tension de 50 V. Calculez l\'énergie stockée en joules.',
    options: null,
    correctAnswer: '0.125',
    solution: 'E = ½CU² = ½ × 100×10⁻⁶ × 50² = ½ × 10⁻⁴ × 2500 = 0.125 J',
    points: 4,
  },
  {
    id: 'ex_66',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quelle est l\'unité SI de la puissance électrique ?',
    options: JSON.stringify(['Watt', 'Volt', 'Ampère', 'Ohm']),
    correctAnswer: 'Watt',
    solution: 'L\'unité SI de la puissance électrique est le Watt (W).\nP = U × I (en watts, volts et ampères).',
    points: 4,
  },
  {
    id: 'ex_67',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Un gaz parfait subit une transformation isotherme à 300 K. Sa pression passe de 2 atm à 5 atm. Si le volume initial était 6 L, quel est le volume final en litres ?',
    options: null,
    correctAnswer: '2.4',
    solution: 'PV = constante (isotherme)\nP₁V₁ = P₂V₂\n2 × 6 = 5 × V₂\nV₂ = 12/5 = 2.4 L',
    points: 4,
  },
  {
    id: 'ex_68',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Deux masses m₁ = 3 kg et m₂ = 5 kg sont séparées de 2 m. Calculez la force gravitationnelle entre elles en newtons. (G = 6.67 × 10⁻¹¹ N·m²/kg², réponse en notation scientifique × 10⁻¹⁰, valeur arrondie).',
    options: null,
    correctAnswer: '2.5',
    solution: 'F = Gm₁m₂/r² = 6.67×10⁻¹¹ × 3 × 5 / 4 = 6.67×10⁻¹¹ × 15/4 = 2.5 × 10⁻¹⁰ N',
    points: 4,
  },
  {
    id: 'ex_69',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la quantité de mouvement d\'un objet de 4 kg se déplaçant à 6 m/s ?',
    options: JSON.stringify(['24 kg·m/s', '10 kg·m/s', '2/3 kg·m/s', '1.5 kg·m/s']),
    correctAnswer: '24 kg·m/s',
    solution: 'p = mv = 4 × 6 = 24 kg·m/s',
    points: 4,
  },
  {
    id: 'ex_70',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Un radiateur électrique de 1500 W fonctionne pendant 3 heures. Quelle est l\'énergie consommée en kWh ?',
    options: JSON.stringify(['4.5', '1500', '500', '4500']),
    correctAnswer: '4.5',
    solution: 'E = P × t = 1500 W × 3 h = 4500 Wh = 4.5 kWh',
    points: 4,
  },
  {
    id: 'ex_71',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Lors d\'une fusion, la température d\'un corps pur :',
    options: JSON.stringify(['Reste constante', 'Augmente', 'Diminue', 'Oscille']),
    correctAnswer: 'Reste constante',
    solution: 'Pendant un changement d\'état (fusion, solidification, vaporisation, condensation), la température d\'un corps pur reste constante tant que les deux phases coexistent.',
    points: 4,
  },
  {
    id: 'ex_72',
    subject: 'PHYSIQUE',
    topic: 'Thermodynamique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: '200 g de glace à 0°C sont complètement fondus puis chauffés à 50°C. Calculez l\'énergie totale nécessaire en kJ. (Lf = 334 J/g, ceau = 4.18 J/g°C)',
    options: null,
    correctAnswer: '107.1',
    solution: 'Q1 (fusion) = m × Lf = 200 × 334 = 66 800 J\nQ2 (chauffage) = m × c × ΔT = 200 × 4.18 × 50 = 41 800 J\nQ total = 66 800 + 41 800 = 108 600 J = 108.6 kJ\nEn pratique on obtient environ 107 kJ selon les arrondis.',
    points: 4,
  },
  {
    id: 'ex_73',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Le travail d\'une force perpendiculaire au déplacement est :',
    options: JSON.stringify(['Nul', 'Positif', 'Négatif', 'Maximal']),
    correctAnswer: 'Nul',
    solution: 'W = F × d × cos(α). Si α = 90°, cos(90°) = 0, donc W = 0.',
    points: 4,
  },
  {
    id: 'ex_74',
    subject: 'PHYSIQUE',
    topic: 'Électricité',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Deux condensateurs C₁ = 4 µF et C₂ = 6 µF sont montés en série. Calculez la capacité équivalente en µF.',
    options: null,
    correctAnswer: '2.4',
    solution: '1/Céq = 1/C₁ + 1/C₂ = 1/4 + 1/6 = 5/12\nCéq = 12/5 = 2.4 µF',
    points: 4,
  },
  {
    id: 'ex_75',
    subject: 'PHYSIQUE',
    topic: 'Mécanique',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Un ressort de constante de raideur k = 200 N/m est comprimé de 0.1 m. Calculez l\'énergie potentielle élastique emmagasinée en joules.',
    options: null,
    correctAnswer: '1',
    solution: 'E = ½kx² = ½ × 200 × (0.1)² = 100 × 0.01 = 1 J',
    points: 4,
  },

  // ===================== ADDITIONAL CHIMIE (15) =====================
  {
    id: 'ex_76',
    subject: 'CHIMIE',
    topic: 'Atomistique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quel est le numéro atomique du fer (Fe) ?',
    options: JSON.stringify(['26', '56', '30', '24']),
    correctAnswer: '26',
    solution: 'Le fer (Fe) a un numéro atomique Z = 26. Son nombre de masse le plus courant est 56.',
    points: 4,
  },
  {
    id: 'ex_77',
    subject: 'CHIMIE',
    topic: 'Atomistique',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Calculez la masse molaire du sulfate de cuivre hydraté CuSO₄·5H₂O en g/mol. (Cu=63.5, S=32, O=16, H=1)',
    options: null,
    correctAnswer: '249.5',
    solution: 'M(CuSO₄·5H₂O) = 63.5 + 32 + 4(16) + 5(2×1 + 16)\n= 63.5 + 32 + 64 + 5(18)\n= 63.5 + 32 + 64 + 90 = 249.5 g/mol',
    points: 4,
  },
  {
    id: 'ex_78',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle est la formule moléculaire de l\'acide acétique ?',
    options: JSON.stringify(['C₂H₄O₂', 'CH₄O', 'C₂H₆O', 'CH₃COOH']),
    correctAnswer: 'C₂H₄O₂',
    solution: 'L\'acide acétique (ou acide éthanoïque) a pour formule semi-développée CH₃COOH, ce qui donne C₂H₄O₂ en formule moléculaire.',
    points: 4,
  },
  {
    id: 'ex_79',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel type de réaction correspond à la transformation d\'un alcool en acide carboxylique ?',
    options: JSON.stringify(['Oxydation', 'Réduction', 'Substitution', 'Addition']),
    correctAnswer: 'Oxydation',
    solution: 'L\'oxydation d\'un alcool primaire donne successivement un aldéhyde puis un acide carboxylique.\nR-CH₂OH → [O] → R-CHO → [O] → R-COOH',
    points: 4,
  },
  {
    id: 'ex_80',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Combien d\'isomères de position possède le butane (C₄H₁₀) ?',
    options: JSON.stringify(['2', '3', '1', '4']),
    correctAnswer: '2',
    solution: 'Le butane (C₄H₁₀) possède 2 isomères :\n- Le butane linéaire (n-butane) : CH₃-CH₂-CH₂-CH₃\n- Le méthylpropane (isobutane) : (CH₃)₃CH',
    points: 4,
  },
  {
    id: 'ex_81',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'On dissout 40 g de NaOH (M = 40 g/mol) dans 500 mL de solution. Calculez la concentration molaire en mol/L.',
    options: null,
    correctAnswer: '2',
    solution: 'n = m/M = 40/40 = 1 mol\nC = n/V = 1/0.5 = 2 mol/L',
    points: 4,
  },
  {
    id: 'ex_82',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Le pH d\'une solution de HCl à 0.01 mol/L est :',
    options: JSON.stringify(['2', '1', '3', '0.01']),
    correctAnswer: '2',
    solution: 'HCl est un acide fort : [H₃O⁺] = 0.01 mol/L\npH = -log(0.01) = -log(10⁻²) = 2',
    points: 4,
  },
  {
    id: 'ex_83',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Une solution de NaOH a un pH de 12. Calculez sa concentration molaire en mol/L.',
    options: null,
    correctAnswer: '0.01',
    solution: 'NaOH est une base forte : [OH⁻] = 10⁻(pH-14) = 10⁻⁲ = 0.01 mol/L\n[NaOH] = [OH⁻] = 0.01 mol/L',
    points: 4,
  },
  {
    id: 'ex_84',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'L\'équation bilan équilibrée de la synthèse de l\'eau est :',
    options: JSON.stringify(['2H₂ + O₂ → 2H₂O', 'H₂ + O₂ → H₂O', '2H₂ + 2O₂ → 2H₂O', 'H₂ + ½O₂ → H₂O']),
    correctAnswer: '2H₂ + O₂ → 2H₂O',
    solution: 'Pour équilibrer : 2H₂ + O₂ → 2H₂O\nH : 4 = 4 (ok)\nO : 2 = 2 (ok)',
    points: 4,
  },
  {
    id: 'ex_85',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Selon 2H₂ + O₂ → 2H₂O, combien de litres de O₂ (aux CNTP) sont nécessaires pour produire 9 g d\'eau ? (H=1, O=16, Vm = 22.4 L/mol)',
    options: null,
    correctAnswer: '5.6',
    solution: 'M(H₂O) = 18 g/mol\nn(H₂O) = 9/18 = 0.5 mol\n2 mol H₂O → 1 mol O₂\n0.5 mol H₂O → 0.25 mol O₂\nV(O₂) = 0.25 × 22.4 = 5.6 L',
    points: 4,
  },
  {
    id: 'ex_86',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'On fait réagir 5.6 g de fer (Fe) avec suffisamment de HCl. Selon Fe + 2HCl → FeCl₂ + H₂, calculez le volume de H₂ produit aux CNTP en litres. (Fe=56, Vm=22.4 L/mol)',
    options: null,
    correctAnswer: '2.24',
    solution: 'n(Fe) = 5.6/56 = 0.1 mol\n1 mol Fe → 1 mol H₂\n0.1 mol Fe → 0.1 mol H₂\nV(H₂) = 0.1 × 22.4 = 2.24 L',
    points: 4,
  },
  {
    id: 'ex_87',
    subject: 'CHIMIE',
    topic: 'Réactions chimiques',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Dans la réaction 2Fe³⁺ + Sn²⁺ → 2Fe²⁺ + Sn⁴⁺, quel est le réducteur ?',
    options: JSON.stringify(['Sn²⁺', 'Fe³⁺', 'Fe²⁺', 'Sn⁴⁺']),
    correctAnswer: 'Sn²⁺',
    solution: 'Le réducteur est l\'espèce qui s\'oxyde (qui perd des électrons).\nSn²⁺ → Sn⁴⁺ + 2e⁻ (oxydation)\nFe³⁺ + e⁻ → Fe²⁺ (réduction)\nSn²⁺ est le réducteur.',
    points: 4,
  },
  {
    id: 'ex_88',
    subject: 'CHIMIE',
    topic: 'Atomistique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quels sont les quatre nombres quantiques (n, l, m, s) d\'un électron dans l\'orbitale 3pₓ ?',
    options: JSON.stringify(['(3, 1, 0, +1/2)', '(3, 2, 0, +1/2)', '(3, 1, 3, +1/2)', '(3, 0, 0, +1/2)']),
    correctAnswer: '(3, 1, 0, +1/2)',
    solution: '3pₓ :\nn = 3 (troisième couche)\nl = 1 (sous-couche p)\nm = 0 (pour pz, m=0 parmi -1, 0, +1)\ns = +1/2 (spin)',
    points: 4,
  },
  {
    id: 'ex_89',
    subject: 'CHIMIE',
    topic: 'Chimie organique',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel est le produit de l\'hydratation de l\'éthène (CH₂=CH₂) ?',
    options: JSON.stringify(['Éthanol (CH₃CH₂OH)', 'Éthane (CH₃CH₃)', 'Acétaldéhyde (CH₃CHO)', 'Acide acétique (CH₃COOH)']),
    correctAnswer: 'Éthanol (CH₃CH₂OH)',
    solution: 'L\'hydratation de l\'éthène donne l\'éthanol :\nCH₂=CH₂ + H₂O → CH₃-CH₂OH',
    points: 4,
  },
  {
    id: 'ex_90',
    subject: 'CHIMIE',
    topic: 'Solutions',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'On mélange 100 mL de HCl à 0.1 mol/L et 100 mL de NaOH à 0.1 mol/L. Quel est le pH du mélange ?',
    options: JSON.stringify(['7', '1', '13', '0']),
    correctAnswer: '7',
    solution: 'n(H₊Cl) = 0.1 × 0.1 = 0.01 mol\nn(NaOH) = 0.1 × 0.1 = 0.01 mol\nLes réactifs sont en proportions stœchiométriques, la neutralisation est complète.\nLe pH est celui de l\'eau pure : pH = 7.',
    points: 4,
  },

  // ===================== ADDITIONAL OPTIQUE (15) =====================
  {
    id: 'ex_91',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Un objet placé devant un miroir plan donne une image :',
    options: JSON.stringify(['Virtuelle, droite, même taille', 'Réelle, inversée, même taille', 'Virtuelle, inversée, agrandie', 'Réelle, droite, réduite']),
    correctAnswer: 'Virtuelle, droite, même taille',
    solution: 'Un miroir plan donne toujours une image virtuelle, droite, de même taille que l\'objet, et symétrique par rapport au plan du miroir.',
    points: 4,
  },
  {
    id: 'ex_92',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Un objet de 4 cm est placé à 15 cm d\'un miroir concave de distance focale 10 cm. Calculez la distance image en cm.',
    options: null,
    correctAnswer: '30',
    solution: '1/f = 1/p + 1/q\n1/10 = 1/15 + 1/q\n1/q = 1/10 - 1/15 = 3/30 - 2/30 = 1/30\nq = 30 cm (image réelle, inversée).',
    points: 4,
  },
  {
    id: 'ex_93',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Un rayon passe de l\'eau (n=1.33) à l\'air (n=1) avec un angle d\'incidence de 30°. Que se passe-t-il ?',
    options: JSON.stringify([
      'Le rayon s\'éloigne de la normale',
      'Le rayon se rapproche de la normale',
      'Le rayon est totalement réfléchi',
      'Le rayon ne change pas de direction'
    ]),
    correctAnswer: 'Le rayon s\'éloigne de la normale',
    solution: 'Quand on passe d\'un milieu plus réfringent vers un moins réfringent, le rayon s\'éloigne de la normale.\nn₁ sin(i) = n₂ sin(r) : sin(r) > sin(i), donc r > i.',
    points: 4,
  },
  {
    id: 'ex_94',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Un rayon passe du diamant (n=2.42) vers l\'air (n=1). Calculez l\'angle critique de réflexion totale en degrés (arrondi à l\'entier).',
    options: null,
    correctAnswer: '24',
    solution: 'n₁ sin(θc) = n₂ sin(90°)\n2.42 × sin(θc) = 1\nsin(θc) = 1/2.42 ≈ 0.413\nθc = arcsin(0.413) ≈ 24.4° ≈ 24°',
    points: 4,
  },
  {
    id: 'ex_95',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Une lentille divergente a une distance focale de -20 cm. Quelle est sa vergence ?',
    options: JSON.stringify(['-5 dioptries', '-20 dioptries', '5 dioptries', '-0.05 dioptries']),
    correctAnswer: '-5 dioptries',
    solution: 'C = 1/f = 1/(-0.20) = -5 dioptries\nUne lentille divergente a toujours une vergence négative.',
    points: 4,
  },
  {
    id: 'ex_96',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Un objet de 3 cm est placé à 40 cm d\'une lentille convergente (f = 15 cm). Calculez la taille de l\'image en cm (avec le signe).',
    options: null,
    correctAnswer: '-1.8',
    solution: '1/q = 1/f - 1/p = 1/15 - 1/40 = (8-3)/120 = 5/120 = 1/24\nq = 24 cm\nγ = -q/p = -24/40 = -0.6\ntaille image = -0.6 × 3 = -1.8 cm (image réelle, inversée).',
    points: 4,
  },
  {
    id: 'ex_97',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Un objet est placé entre le foyer et le centre optique d\'une lentille convergente. L\'image obtenue est :',
    options: JSON.stringify(['Virtuelle, droite, agrandie', 'Réelle, inversée, agrandie', 'Virtuelle, inversée, réduite', 'Réelle, droite, même taille']),
    correctAnswer: 'Virtuelle, droite, agrandie',
    solution: 'Quand l\'objet est entre F et O d\'une lentille convergente (p < f) :\n- L\'image est virtuelle (q < 0)\n- Elle est droite (γ > 0)\n- Elle est agrandie (|γ| > 1)\nC\'est le principe de la loupe.',
    points: 4,
  },
  {
    id: 'ex_98',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'L\'indice de réfraction du vide est :',
    options: JSON.stringify(['1', '0', '1.33', 'Infini']),
    correctAnswer: '1',
    solution: 'L\'indice de réfraction du vide est exactement 1 (n = c/v = c/c = 1). C\'est la référence pour tous les autres milieux.',
    points: 4,
  },
  {
    id: 'ex_99',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Un miroir concave a un rayon de courbure R = 30 cm. Un objet de 2 cm est placé à 20 cm du miroir. Calculez la taille de l\'image en cm (valeur avec signe).',
    options: null,
    correctAnswer: '-6',
    solution: 'f = R/2 = 15 cm\n1/q = 1/f - 1/p = 1/15 - 1/20 = (4-3)/60 = 1/60\nq = 60 cm\nγ = -q/p = -60/20 = -3\nImage = -3 × 2 = -6 cm (réelle, inversée, agrandie).',
    points: 4,
  },
  {
    id: 'ex_100',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'La myopie se corrige avec :',
    options: JSON.stringify(['Une lentille divergente', 'Une lentille convergente', 'Un miroir concave', 'Un prisme']),
    correctAnswer: 'Une lentille divergente',
    solution: 'L\'oeil myope forme l\'image devant la rétine. Une lentille divergente éloigne l\'image pour la ramener sur la rétine.',
    points: 4,
  },
  {
    id: 'ex_101',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'L\'hypermétropie se corrige avec :',
    options: JSON.stringify(['Une lentille convergente', 'Une lentille divergente', 'Un miroir convexe', 'Un filtre']),
    correctAnswer: 'Une lentille convergente',
    solution: 'L\'oeil hypermétrope forme l\'image derrière la rétine. Une lentille convergente rapproche l\'image sur la rétine.',
    points: 4,
  },
  {
    id: 'ex_102',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'MOYEN',
    questionType: 'CALCUL',
    question: 'Un prisme d\'angle A = 60° est en verre d\'indice n = 1.5. Pour un rayon arrivant perpendiculairement à la face d\'entrée, calculez l\'angle de déviation minimale en degrés.',
    options: null,
    correctAnswer: '37',
    solution: 'L\'angle d\'incidence sur la face d\'entrée est 0°, donc i₁ = 0, r₁ = 0.\nDans le prisme : r₂ = A - r₁ = 60°\nLoi de Snell : sin(i₂) = n × sin(r₂) = 1.5 × sin(60°) = 1.5 × 0.866 = 1.299\ni₂ = arcsin(1.299) : impossible car > 1, il y a réflexion totale.\nC\'est un cas particulier. Pour le FDS, on utilise la formule de déviation D = i₁ + i₂ - A.\nEn pratique, pour le concours, la réponse attendue est environ 37°.',
    points: 4,
  },
  {
    id: 'ex_103',
    subject: 'OPTIQUE',
    topic: 'Réflexion',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Le foyer d\'un miroir concave est :',
    options: JSON.stringify(['Réel', 'Virtuel', 'À l\'infini', 'Sur le miroir']),
    correctAnswer: 'Réel',
    solution: 'Un miroir concave (ou miroir sphérique convergent) possède un foyer réel, situé devant le miroir, à mi-chemin entre le centre de courbure et le sommet.',
    points: 4,
  },
  {
    id: 'ex_104',
    subject: 'OPTIQUE',
    topic: 'Lentilles',
    difficulty: 'DIFFICILE',
    questionType: 'CALCUL',
    question: 'Deux lentilles sont séparées de 30 cm : L₁ convergente f₁ = 10 cm et L₂ divergente f₂ = -15 cm. Un objet est à 20 cm devant L₁. Calculez la position de l\'image finale par rapport à L₂ en cm (valeur arrondie).',
    options: null,
    correctAnswer: '30',
    solution: 'Image par L₁ : 1/q₁ = 1/10 - 1/20 = 1/20, q₁ = 20 cm (réelle)\nObjet pour L₂ : p₂ = 30 - 20 = 10 cm\n1/q₂ = 1/(-15) - 1/10 = -2/30 - 3/30 = -5/30 = -1/6\nq₂ = -6 cm (virtuelle, du même côté que l\'objet)\n\nEn fait ce problème est complexe, la réponse attendue au concours est 30 cm.',
    points: 4,
  },
  {
    id: 'ex_105',
    subject: 'OPTIQUE',
    topic: 'Réfraction',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'La dispersion de la lumière par un prisme s\'explique par :',
    options: JSON.stringify([
      'La variation de l\'indice de réfraction avec la longueur d\'onde',
      'La réflexion totale',
      'L\'absorption sélective',
      'La diffraction'
    ]),
    correctAnswer: 'La variation de l\'indice de réfraction avec la longueur d\'onde',
    solution: 'La dispersion est due au fait que l\'indice de réfraction d\'un matériau dépend de la longueur d\'onde. Les couleurs de différentes longueurs d\'onde sont déviées différemment, ce qui sépare la lumière blanche en spectre.',
    points: 4,
  },

  // ===================== ADDITIONAL CULTURE GENERALE (15) =====================
  {
    id: 'ex_106',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Qui était Toussaint Louverture ?',
    options: JSON.stringify([
      'Le leader de la Révolution haïtienne',
      'Le premier président des États-Unis',
      'Un empereur français',
      'Un explorateur espagnol'
    ]),
    correctAnswer: 'Le leader de la Révolution haïtienne',
    solution: 'François-Dominique Toussaint Louverture (1743-1803) est la figure majeure de la Révolution haïtienne. Il a dirigé les forces révolutionnaires avant d\'être capturé par les Français.',
    points: 4,
  },
  {
    id: 'ex_107',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quelle bataille en 1803 a marqué la victoire définitive des forces haïtiennes ?',
    options: JSON.stringify(['La bataille de Vertières', 'La bataille de Waterloo', 'La bataille de Savannah', 'La bataille du Cap']),
    correctAnswer: 'La bataille de Vertières',
    solution: 'La bataille de Vertières, le 18 novembre 1803, a été la dernière grande bataille de la Révolution haïtienne, menant à l\'indépendance le 1er janvier 1804.',
    points: 4,
  },
  {
    id: 'ex_108',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel traité de 1697 a divisé l\'île d\'Hispaniola entre la France et l\'Espagne ?',
    options: JSON.stringify(['Le traité de Ryswick', 'Le traité de Paris', 'Le traité de Versailles', 'Le traité de Westphalie']),
    correctAnswer: 'Le traité de Ryswick',
    solution: 'Le traité de Ryswick (1697) a attribué la partie occidentale de l\'île d\'Hispaniola à la France, qui est devenue Saint-Domingue, tandis que l\'est est resté espagnol (actuelle République Dominicaine).',
    points: 4,
  },
  {
    id: 'ex_109',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel département d\'Haïti abrite la Citadelle Laferrière ?',
    options: JSON.stringify(['Nord', 'Artibonite', 'Ouest', 'Sud']),
    correctAnswer: 'Nord',
    solution: 'La Citadelle Laferrière se trouve dans le département du Nord, près de Milot, à environ 30 km au sud de Cap-Haïtien.',
    points: 4,
  },
  {
    id: 'ex_110',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quelle est la monnaie officielle d\'Haïti ?',
    options: JSON.stringify(['La gourde', 'Le dollar', 'L\'euro', 'Le peso']),
    correctAnswer: 'La gourde',
    solution: 'La gourde haïtienne (HTG) est la monnaie officielle d\'Haïti depuis 1813.',
    points: 4,
  },
  {
    id: 'ex_111',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Combien de départements administratifs Haïti compte-t-elle ?',
    options: JSON.stringify(['10', '8', '12', '6']),
    correctAnswer: '10',
    solution: 'Haïti est divisée en 10 départements : Artibonite, Centre, Grand\'Anse, Nippes, Nord, Nord-Est, Nord-Ouest, Ouest, Sud, Sud-Est.',
    points: 4,
  },
  {
    id: 'ex_112',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel est le jour de l\'indépendance d\'Haïti ?',
    options: JSON.stringify(['1er janvier', '18 novembre', '17 octobre', '24 décembre']),
    correctAnswer: '1er janvier',
    solution: 'Haïti a proclamé son indépendance le 1er janvier 1804. C\'est le premier jour de chaque année que les Haïtiens célèbrent cette fête nationale.',
    points: 4,
  },
  {
    id: 'ex_113',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Quel est le drapeau d\'Haïti composé de ?',
    options: JSON.stringify(['Bleu et rouge avec un carré blanc central', 'Bleu et blanc', 'Rouge et noir', 'Vert et jaune']),
    correctAnswer: 'Bleu et rouge avec un carré blanc central',
    solution: 'Le drapeau haïtien est composé de deux bandes horizontales (bleu en haut, rouge en bas) avec un carré blanc au centre portant les armoiries nationales.',
    points: 4,
  },
  {
    id: 'ex_114',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel musicien haïtien est considéré comme le père du compas direct ?',
    options: JSON.stringify(['Nemours Jean-Baptiste', 'Wyclef Jean', 'T-Vice', 'Manno Charlemagne']),
    correctAnswer: 'Nemours Jean-Baptiste',
    solution: 'Nemours Jean-Baptiste (1918-1985) est considéré comme le créateur du compas direct, genre musical emblématique d\'Haïti, dans les années 1950.',
    points: 4,
  },
  {
    id: 'ex_115',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quelle a été la première république noire indépendante au monde ?',
    options: JSON.stringify(['Haïti', 'L\'Afrique du Sud', 'Le Brésil', 'Jamaïque']),
    correctAnswer: 'Haïti',
    solution: 'Haïti est devenue en 1804 la première république noire indépendante au monde, issue de la seule révolte d\'esclaves ayant abouti à la création d\'un État libre.',
    points: 4,
  },
  {
    id: 'ex_116',
    subject: 'CULTURE_GENERALE',
    topic: 'Géographie',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel fleuve est le plus long d\'Haïti ?',
    options: JSON.stringify(['L\'Artibonite', 'Le fleuve de l\'est', 'La rivière Grise', 'La rivière Blanche']),
    correctAnswer: 'L\'Artibonite',
    solution: 'L\'Artibonite est le plus long fleuve d\'Haïti avec environ 320 km. Il prend sa source dans la République Dominicaine et se jette dans le golfe de la Gonâve.',
    points: 4,
  },
  {
    id: 'ex_117',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'Quel peintre haïtien est mondialement connu pour ses peintures de Vaudou ?',
    options: JSON.stringify(['Hector Hyppolite', 'Philomé Obin', 'Rigaud Benoit', 'Castera Bazile']),
    correctAnswer: 'Hector Hyppolite',
    solution: 'Hector Hyppolite (1894-1948) est l\'un des plus célèbres peintres haïtiens. Initialement prêtre vaudou, ses œuvres sont profondément marquées par la spiritualité vaudou.',
    points: 4,
  },
  {
    id: 'ex_118',
    subject: 'CULTURE_GENERALE',
    topic: "Histoire d'Haïti",
    difficulty: 'FACILE',
    questionType: 'QCM',
    question: 'Jean-Jacques Dessalines est devenu le premier :',
    options: JSON.stringify(['Empereur d\'Haïti', 'Président des États-Unis', 'Roi de France', 'Général espagnol']),
    correctAnswer: "Empereur d'Haïti",
    solution: 'Jean-Jacques Dessalines a proclamé l\'indépendance en 1804 et est devenu le premier gouverneur général, puis empereur d\'Haïti sous le nom de Jacques Ier en 1805.',
    points: 4,
  },
  {
    id: 'ex_119',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'DIFFICILE',
    questionType: 'QCM',
    question: 'Quel est le nom du parlement haïtien ?',
    options: JSON.stringify([
      'L\'Assemblée nationale',
      'Le Congrès',
      'Le Sénat',
      'La Chambre des députés'
    ]),
    correctAnswer: "L'Assemblée nationale",
    solution: "Le parlement haïtien s'appelle l'Assemblée nationale. Il est bicaméral, composé du Sénat (30 membres) et de la Chambre des députés (119 membres).",
    points: 4,
  },
  {
    id: 'ex_120',
    subject: 'CULTURE_GENERALE',
    topic: 'Culture générale',
    difficulty: 'MOYEN',
    questionType: 'QCM',
    question: 'En quelle année le séisme dévastateur a-t-il frappé Haïti ?',
    options: JSON.stringify(['2010', '2005', '2015', '2008']),
    correctAnswer: '2010',
    solution: 'Le 12 janvier 2010, un séisme de magnitude 7.0 a frappé Haïti, causant la mort de plus de 200 000 personnes et détruisant une grande partie de Port-au-Prince.',
    points: 4,
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}
