import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

const EXERCISES = [
    // ===================== MATHEMATIQUES =====================
    // --- Algèbre ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Algèbre',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Résolvez l\'équation : 2x + 6 = 14',
      options: JSON.stringify(['x = 2', 'x = 4', 'x = 6', 'x = 10']),
      correctAnswer: 'x = 4',
      solution: '2x + 6 = 14\n2x = 14 - 6\n2x = 8\nx = 8 / 2\nx = 4\n\nVérification : 2(4) + 6 = 8 + 6 = 14 ✓',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Algèbre',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quel est le résultat de (3x + 2)(x - 1) ?',
      options: JSON.stringify(['3x² - x - 2', '3x² + x - 2', '3x² - 3x - 2', '3x² - x + 2']),
      correctAnswer: '3x² - x - 2',
      solution: '(3x + 2)(x - 1)\n= 3x × x + 3x × (-1) + 2 × x + 2 × (-1)\n= 3x² - 3x + 2x - 2\n= 3x² - x - 2',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Algèbre',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Si f(x) = x² - 4x + 3, quelles sont les racines de f(x) = 0 ?',
      options: JSON.stringify(['x = 1 et x = 3', 'x = -1 et x = -3', 'x = 2 et x = 6', 'x = -2 et x = 2']),
      correctAnswer: 'x = 1 et x = 3',
      solution: 'x² - 4x + 3 = 0\nOn utilise le discriminant : Δ = b² - 4ac = (-4)² - 4(1)(3) = 16 - 12 = 4\nΔ > 0, donc deux racines :\nx₁ = (4 - √4) / 2 = (4 - 2) / 2 = 1\nx₂ = (4 + √4) / 2 = (4 + 2) / 2 = 3\n\nLes racines sont x = 1 et x = 3.',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Algèbre',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Résolvez le système :\n2x + y = 7\nx - y = 2\nDonnez la valeur de x et y séparées par une virgule (ex: 3, 1)',
      options: null,
      correctAnswer: '3, 1',
      solution: 'Système :\n2x + y = 7 ...(1)\nx - y = 2 ...(2)\n\nMéthode d\'addition : (1) + (2) :\n2x + y + x - y = 7 + 2\n3x = 9\nx = 3\n\nDans (2) : 3 - y = 2 → y = 1\n\nVérification : 2(3) + 1 = 7 ✓ et 3 - 1 = 2 ✓',
      points: 4,
    },
    // --- Géométrie ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quelle est l\'aire d\'un triangle de base 10 cm et de hauteur 6 cm ?',
      options: JSON.stringify(['60 cm²', '30 cm²', '16 cm²', '36 cm²']),
      correctAnswer: '30 cm²',
      solution: 'Aire du triangle = (base × hauteur) / 2\n= (10 × 6) / 2\n= 60 / 2\n= 30 cm²',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Dans un cercle de rayon 5 cm, quelle est la longueur d\'un arc de 60° ?',
      options: JSON.stringify(['(5π/3) cm', '(10π/3) cm', '(25π/6) cm', '5π cm']),
      correctAnswer: '(5π/3) cm',
      solution: 'Longueur de l\'arc = (θ/360) × 2πr\n= (60/360) × 2π × 5\n= (1/6) × 10π\n= 10π/6\n= 5π/3 cm',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Un cylindre a un volume de 200π cm³ et un rayon de 5 cm. Calculez sa hauteur en cm.',
      options: null,
      correctAnswer: '8',
      solution: 'Volume du cylindre = πr²h\n200π = π × 5² × h\n200π = 25π × h\nh = 200π / (25π)\nh = 200 / 25\nh = 8 cm',
      points: 4,
    },
    // --- Trigonométrie ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Trigonométrie',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Dans un triangle rectangle, si l\'angle θ = 30° et l\'hypoténuse = 10, que vaut le côté adjacent ?',
      options: JSON.stringify(['5√3', '5', '10√3', '10']),
      correctAnswer: '5√3',
      solution: 'cos(30°) = adjacent / hypoténuse\ncos(30°) = √3/2\n\nadjacent = hypoténuse × cos(30°)\n= 10 × (√3/2)\n= 5√3',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Trigonométrie',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est la valeur de sin²(α) + cos²(α) ?',
      options: JSON.stringify(['1', '0', '2', 'tan(α)']),
      correctAnswer: '1',
      solution: 'sin²(α) + cos²(α) = 1 est une identité trigonométrique fondamentale.',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Trigonométrie',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Simplifiez l\'expression : (sin(2x)) / (2sin(x)cos(x)). Donnez votre réponse sous forme de nombre.',
      options: null,
      correctAnswer: '1',
      solution: 'On sait que sin(2x) = 2sin(x)cos(x) (formule du double angle).\n\nDonc : sin(2x) / (2sin(x)cos(x))\n= 2sin(x)cos(x) / (2sin(x)cos(x))\n= 1',
      points: 4,
    },
    // --- Analyse ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Analyse',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est la dérivée de f(x) = 3x⁴ - 2x² + 5x - 1 ?',
      options: JSON.stringify(['12x³ - 4x + 5', '12x³ - 2x + 5', '3x³ - 4x + 5', '12x⁴ - 4x + 5']),
      correctAnswer: '12x³ - 4x + 5',
      solution: 'f(x) = 3x⁴ - 2x² + 5x - 1\nf\'(x) = 4 × 3x³ - 2 × 2x + 5 - 0\n= 12x³ - 4x + 5',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Analyse',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Calculez l\'intégrale définie de f(x) = 2x + 1 de x=0 à x=3.',
      options: null,
      correctAnswer: '12',
      solution: '∫₀³ (2x + 1) dx = [x² + x]₀³\n= (3² + 3) - (0² + 0)\n= (9 + 3) - 0\n= 12',
      points: 4,
    },
    // --- Probabilités ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Probabilités',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'On lance un dé à 6 faces. Quelle est la probabilité d\'obtenir un nombre pair ?',
      options: JSON.stringify(['1/2', '1/3', '1/6', '2/3']),
      correctAnswer: '1/2',
      solution: 'Nombres pairs sur un dé : {2, 4, 6} → 3 résultats favorables\nNombre total de résultats possibles : 6\n\nP(pair) = 3/6 = 1/2',
      points: 4,
    },
    // --- Géométrie analytique ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie analytique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: "Quelle est l'équation cartésienne de la droite passant par A(2, 3) et B(-1, 0) ?",
      options: JSON.stringify(['y = x + 1', 'y = -x + 5', 'y = x - 1', 'y = -x - 1']),
      correctAnswer: 'y = x + 1',
      solution: 'Pente : m = (0 - 3) / (-1 - 2) = -3 / -3 = 1\nÉquation : y - y_A = m(x - x_A)\ny - 3 = 1(x - 2)\ny = x + 1',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie analytique',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: "Soit le cercle d'équation x² + y² - 4x + 6y - 3 = 0. Calculez son rayon.",
      options: null,
      correctAnswer: '4',
      solution: 'Forme canonique : (x - a)² + (y - b)² = R²\nx² - 4x + y² + 6y = 3\nx² - 4x + 4 + y² + 6y + 9 = 3 + 4 + 9\n(x - 2)² + (y + 3)² = 16\n\nR² = 16 donc R = 4',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Géométrie analytique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'La parabole d\'équation y = x² - 4x + 3 a pour sommet :',
      options: JSON.stringify(['S(2, -1)', 'S(2, 1)', 'S(-2, -1)', 'S(1, 0)']),
      correctAnswer: 'S(2, -1)',
      solution: 'y = x² - 4x + 3\ny = (x - 2)² - 4 + 3\ny = (x - 2)² - 1\n\nSous forme (x - a)² + k, le sommet est S(a, k) = S(2, -1)',
      points: 4,
    },
    // --- Suites numériques ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Suites numériques',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Soit la suite arithmétique (u_n) de premier terme u_0 = 3 et de raison r = 5. Quelle est la valeur de u_20 ?',
      options: JSON.stringify(['103', '105', '100', '108']),
      correctAnswer: '103',
      solution: 'Formule : u_n = u_0 + n × r\nu_20 = 3 + 20 × 5\nu_20 = 3 + 100\nu_20 = 103',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Suites numériques',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Soit la suite géométrique (v_n) de premier terme v_1 = 2 et de raison q = 3. Calculez la somme des 5 premiers termes S_5.',
      options: null,
      correctAnswer: '242',
      solution: 'S_n = v_1 × (q^n - 1) / (q - 1)\nS_5 = 2 × (3^5 - 1) / (3 - 1)\nS_5 = 2 × (243 - 1) / 2\nS_5 = 2 × 242 / 2\nS_5 = 242',
      points: 4,
    },
    // --- Limites et fonctions ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Limites',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quelle est la limite de f(x) = (2x + 1) / (x - 3) lorsque x tend vers +∞ ?',
      options: JSON.stringify(['2', '0', '+∞', '-∞']),
      correctAnswer: '2',
      solution: 'Pour x → +∞, on divise le numérateur et le dénominateur par x :\nf(x) = (2 + 1/x) / (1 - 3/x)\nQuand x → +∞ : 1/x → 0 et 3/x → 0\nf(x) → (2 + 0) / (1 - 0) = 2',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Limites',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Calculez la limite de (sin(3x)) / x lorsque x tend vers 0. Donnez la valeur numérique.',
      options: null,
      correctAnswer: '3',
      solution: 'On sait que lim(sin(x)/x) = 1 quand x → 0.\nlim(sin(3x)/x) = 3 × lim(sin(3x)/(3x)) = 3 × 1 = 3',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Limites',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est la dérivée de f(x) = sin(2x) ?',
      options: JSON.stringify(['2cos(2x)', '-2cos(2x)', 'cos(2x)', '2sin(2x)cos(2x)']),
      correctAnswer: '2cos(2x)',
      solution: 'f(x) = sin(2x)\nf\'(x) = cos(2x) × 2\nf\'(x) = 2cos(2x)',
      points: 4,
    },
    // --- Nombres complexes ---
    {
      subject: 'MATHEMATIQUES',
      topic: 'Nombres complexes',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quel est le module du nombre complexe z = 3 + 4i ?',
      options: JSON.stringify(['5', '7', '25', '√7']),
      correctAnswer: '5',
      solution: '|z| = √(a² + b²)\n|z| = √(3² + 4²)\n|z| = √(9 + 16)\n|z| = √25 = 5',
      points: 4,
    },
    {
      subject: 'MATHEMATIQUES',
      topic: 'Nombres complexes',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Soit z1 = 1 + i et z2 = 2 - i. Calculez le module du produit z1 × z2.',
      options: null,
      correctAnswer: '√10',
      solution: 'Propriété : |z1 × z2| = |z1| × |z2|\n|z1| = √(1² + 1²) = √2\n|z2| = √(2² + (-1)²) = √5\n|z1 × z2| = √2 × √5 = √10',
      points: 4,
    },

    // ===================== PHYSIQUE =====================
    // --- Mécanique ---
    {
      subject: 'PHYSIQUE',
      topic: 'Mécanique',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Un objet de masse 5 kg est soumis à une force de 20 N. Quelle est son accélération ?',
      options: JSON.stringify(['4 m/s²', '100 m/s²', '0.25 m/s²', '15 m/s²']),
      correctAnswer: '4 m/s²',
      solution: 'Deuxième loi de Newton : F = ma\nDonc : a = F/m\na = 20 N / 5 kg\na = 4 m/s²',
      points: 4,
    },
    {
      subject: 'PHYSIQUE',
      topic: 'Mécanique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Une balle est lancée verticalement vers le haut avec une vitesse initiale de 20 m/s. Quelle hauteur maximale atteint-elle ? (g = 10 m/s²)',
      options: JSON.stringify(['20 m', '10 m', '40 m', '200 m']),
      correctAnswer: '20 m',
      solution: 'Au point le plus haut, la vitesse finale v = 0.\nv² = v₀² - 2gh\n0 = (20)² - 2(10)h\n20h = 400\nh = 20 m',
      points: 4,
    },
    {
      subject: 'PHYSIQUE',
      topic: 'Mécanique',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Un bloc de 2 kg glisse sur un plan incliné à 30° sans frottement. Quelle est l\'accélération du bloc en m/s² ? (g = 10 m/s²). Donnez la valeur numérique uniquement.',
      options: null,
      correctAnswer: '5',
      solution: 'F = mg sin(θ) = 2 × 10 × sin(30°) = 20 × 0.5 = 10 N\na = F/m = 10/2 = 5 m/s²',
      points: 4,
    },
    // --- Électricité ---
    {
      subject: 'PHYSIQUE',
      topic: 'Électricité',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Dans un circuit, une résistance de 10 Ω est traversée par un courant de 2 A. Quelle est la tension à ses bornes ?',
      options: JSON.stringify(['20 V', '5 V', '0.2 V', '12 V']),
      correctAnswer: '20 V',
      solution: 'Loi d\'Ohm : U = RI\nU = 10 Ω × 2 A\nU = 20 V',
      points: 4,
    },
    {
      subject: 'PHYSIQUE',
      topic: 'Électricité',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Trois résistances de 6 Ω chacune sont montées en parallèle. Quelle est la résistance équivalente ?',
      options: JSON.stringify(['2 Ω', '18 Ω', '6 Ω', '3 Ω']),
      correctAnswer: '2 Ω',
      solution: '1/R_eq = 1/R₁ + 1/R₂ + 1/R₃\n1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2\nR_eq = 2 Ω',
      points: 4,
    },
    {
      subject: 'PHYSIQUE',
      topic: 'Électricité',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Un générateur de force électromotrice E = 12 V et de résistance interne r = 1 Ω alimente une résistance R = 5 Ω. Calculez l\'intensité du courant en ampères.',
      options: null,
      correctAnswer: '2',
      solution: 'Loi de Pouillet : I = E / (R + r)\nI = 12 / (5 + 1)\nI = 12 / 6\nI = 2 A',
      points: 4,
    },
    // --- Thermodynamique ---
    {
      subject: 'PHYSIQUE',
      topic: 'Thermodynamique',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Combien de joules faut-il pour élever la température de 200 g d\'eau de 20°C à 70°C ? (c = 4,18 J/g·°C)',
      options: JSON.stringify(['41 800 J', '20 900 J', '4 180 J', '83 600 J']),
      correctAnswer: '41 800 J',
      solution: 'Q = mcΔT\nQ = 200 × 4,18 × (70 - 20)\nQ = 200 × 4,18 × 50\nQ = 41 800 J',
      points: 4,
    },
    {
      subject: 'PHYSIQUE',
      topic: 'Thermodynamique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Un gaz parfait à 300 K occupe un volume de 2 L sous une pression de 1 atm. Quel volume occupe-t-il à 600 K sous la même pression ?',
      options: JSON.stringify(['4 L', '2 L', '1 L', '8 L']),
      correctAnswer: '4 L',
      solution: 'Loi de Charles (P constante) : V₁/T₁ = V₂/T₂\nV₂ = V₁ × T₂/T₁\nV₂ = 2 × 600/300\nV₂ = 2 × 2 = 4 L',
      points: 4,
    },

    // ===================== CHIMIE =====================
    // --- Atomistique ---
    {
      subject: 'CHIMIE',
      topic: 'Atomistique',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quel est le nombre de neutrons dans un atome de carbone ¹⁴C (Z=6) ?',
      options: JSON.stringify(['8', '6', '14', '20']),
      correctAnswer: '8',
      solution: 'Nombre de neutrons = A - Z\nA = nombre de masse = 14\nZ = numéro atomique = 6\nN = 14 - 6 = 8 neutrons',
      points: 4,
    },
    {
      subject: 'CHIMIE',
      topic: 'Atomistique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est la configuration électronique du potassium (K, Z=19) dans son état fondamental ?',
      options: JSON.stringify([
        '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
        '1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹',
        '1s² 2s² 2p⁶ 3s² 3p⁷',
        '1s² 2s² 2p⁶ 3s² 3p⁶ 4s²',
      ]),
      correctAnswer: '1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹',
      solution: 'Le potassium a 19 électrons.\n1s² (2) → 2s² (4) → 2p⁶ (10) → 3s² (12) → 3p⁶ (18) → 4s¹ (19)\nNote : 4s se remplit avant 3d car 4s a une énergie plus basse.',
      points: 4,
    },
    // --- Chimie organique ---
    {
      subject: 'CHIMIE',
      topic: 'Chimie organique',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quel est le nom de l\'alcane ayant la formule C₃H₈ ?',
      options: JSON.stringify(['Propane', 'Méthane', 'Éthane', 'Butane']),
      correctAnswer: 'Propane',
      solution: 'Formule générale des alcanes : CₙH₂ₙ₊₂\nPour C₃H₈ : n = 3\nPréfixe pour 3 carbones : "prop" → Propane',
      points: 4,
    },
    {
      subject: 'CHIMIE',
      topic: 'Chimie organique',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est la fonction organique caractérisée par le groupe -CHO ?',
      options: JSON.stringify(['Aldéhyde', 'Acide carboxylique', 'Alcool', 'Cétone']),
      correctAnswer: 'Aldéhyde',
      solution: 'Le groupe -CHO est le groupe fonctionnel des aldéhydes.\n- -OH : Alcool\n- -CHO : Aldéhyde\n- -CO- : Cétone\n- -COOH : Acide carboxylique',
      points: 4,
    },
    // --- Solutions ---
    {
      subject: 'CHIMIE',
      topic: 'Solutions',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'On dissout 10 g de NaCl dans 500 mL d\'eau. Quelle est la concentration massique en g/L ?',
      options: JSON.stringify(['20 g/L', '10 g/L', '0.02 g/L', '50 g/L']),
      correctAnswer: '20 g/L',
      solution: 'Cm = m / V\nm = 10 g\nV = 500 mL = 0.5 L\nCm = 10 / 0.5 = 20 g/L',
      points: 4,
    },
    {
      subject: 'CHIMIE',
      topic: 'Solutions',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'On prépare 250 mL d\'une solution de HCl à 0.5 mol/L à partir d\'une solution mère à 2 mol/L. Quel volume en mL de solution mère faut-il prélever ?',
      options: null,
      correctAnswer: '62.5',
      solution: 'Dilution : C₁V₁ = C₂V₂\nV₁ = C₂V₂ / C₁ = (0.5 × 250) / 2 = 125 / 2 = 62.5 mL',
      points: 4,
    },
    // --- Réactions chimiques ---
    {
      subject: 'CHIMIE',
      topic: 'Réactions chimiques',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quelle est l\'équation bilan équilibrée de la combustion du méthane CH₄ ?',
      options: JSON.stringify([
        'CH₄ + 2O₂ → CO₂ + 2H₂O',
        'CH₄ + O₂ → CO₂ + H₂O',
        '2CH₄ + 4O₂ → 2CO₂ + 4H₂O',
        'CH₄ + 2O₂ → CO + 2H₂O',
      ]),
      correctAnswer: 'CH₄ + 2O₂ → CO₂ + 2H₂O',
      solution: 'CH₄ + O₂ → CO₂ + H₂O\nC : 1 → 1 (ok)\nH : 4 → 2×2 = 4 (ok)\nO : 2×2 = 4 → 2+2 = 4 (ok)\nÉquation : CH₄ + 2O₂ → CO₂ + 2H₂O',
      points: 4,
    },
    {
      subject: 'CHIMIE',
      topic: 'Réactions chimiques',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Selon l\'équation N₂ + 3H₂ → 2NH₃, combien de grammes de NH₃ peuvent être produits à partir de 14 g de N₂ ? (N=14, H=1). Donnez la valeur en grammes.',
      options: null,
      correctAnswer: '17',
      solution: 'M(N₂) = 2×14 = 28 g/mol\nn(N₂) = 14/28 = 0.5 mol\n1 mol N₂ → 2 mol NH₃\n0.5 mol N₂ → 1 mol NH₃\nM(NH₃) = 14 + 3×1 = 17 g/mol\nm(NH₃) = 1 × 17 = 17 g',
      points: 4,
    },

    // ===================== OPTIQUE =====================
    {
      subject: 'OPTIQUE',
      topic: 'Réflexion',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Un rayon lumineux frappe un miroir plan avec un angle d\'incidence de 40°. Quel est l\'angle de réflexion ?',
      options: JSON.stringify(['40°', '50°', '80°', '20°']),
      correctAnswer: '40°',
      solution: 'Première loi de la réflexion : l\'angle de réflexion est toujours égal à l\'angle d\'incidence = 40°',
      points: 4,
    },
    {
      subject: 'OPTIQUE',
      topic: 'Réflexion',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Un objet de 5 cm est placé à 10 cm d\'un miroir concave de distance focale 5 cm. Quelle est la taille de l\'image ?',
      options: JSON.stringify(['5 cm (image réelle inversée)', '5 cm (image virtuelle droite)', '10 cm (image réelle inversée)', '2.5 cm (image virtuelle droite)']),
      correctAnswer: '5 cm (image réelle inversée)',
      solution: '1/f = 1/p + 1/q → 1/5 = 1/10 + 1/q → q = 10 cm\nγ = -q/p = -10/10 = -1\n|image| = 1 × 5 = 5 cm, inversée.',
      points: 4,
    },
    {
      subject: 'OPTIQUE',
      topic: 'Réfraction',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Un rayon passe de l\'air (n=1) vers l\'eau (n=1.33) avec un angle d\'incidence de 30°. Que se passe-t-il ?',
      options: JSON.stringify([
        'Le rayon se rapproche de la normale',
        'Le rayon s\'éloigne de la normale',
        'Le rayon est totalement réfléchi',
        'Le rayon ne change pas de direction',
      ]),
      correctAnswer: 'Le rayon se rapproche de la normale',
      solution: 'n₁ sin(i) = n₂ sin(r)\n1 × sin(30°) = 1.33 × sin(r)\nsin(r) = 0.5 / 1.33 ≈ 0.376\nr ≈ 22° < i : le rayon se rapproche de la normale.',
      points: 4,
    },
    {
      subject: 'OPTIQUE',
      topic: 'Réfraction',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Calculez l\'angle critique pour la réflexion totale entre le verre (n=1.5) et l\'air (n=1). Donnez la valeur en degrés (arrondie à l\'entier le plus proche).',
      options: null,
      correctAnswer: '42',
      solution: 'n₁ sin(θc) = n₂ sin(90°)\n1.5 × sin(θc) = 1\nsin(θc) = 1/1.5 = 0.667\nθc = arcsin(0.667) ≈ 41.8° ≈ 42°',
      points: 4,
    },
    {
      subject: 'OPTIQUE',
      topic: 'Lentilles',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Une lentille convergente a une distance focale de 20 cm. Où se forme l\'image d\'un objet placé à 60 cm de la lentille ?',
      options: JSON.stringify(['30 cm de la lentille', '60 cm de la lentille', '20 cm de la lentille', '15 cm de la lentille']),
      correctAnswer: '30 cm de la lentille',
      solution: '1/f = 1/p + 1/q\n1/20 = 1/60 + 1/q\n1/q = 1/20 - 1/60 = 2/60 = 1/30\nq = 30 cm (image réelle).',
      points: 4,
    },
    {
      subject: 'OPTIQUE',
      topic: 'Lentilles',
      difficulty: 'DIFFICILE',
      questionType: 'CALCUL',
      question: 'Deux lentilles convergentes de distances focales f₁ = 10 cm et f₂ = 20 cm sont accolées. Quelle est la vergence totale en dioptries ?',
      options: null,
      correctAnswer: '15',
      solution: 'C = C₁ + C₂ = 1/f₁ + 1/f₂\nC = 1/0.10 + 1/0.20 = 10 + 5 = 15 dioptries',
      points: 4,
    },

    // ===================== CULTURE GENERALE =====================
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Histoire d\'Haïti',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'En quelle année Haïti a-t-elle proclamé son indépendance ?',
      options: JSON.stringify(['1804', '1791', '1802', '1815']),
      correctAnswer: '1804',
      solution: 'Haïti a proclamé son indépendance le 1er janvier 1804, sous la direction de Jean-Jacques Dessalines.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Histoire d\'Haïti',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Qui est considéré comme le père de la nation haïtienne ?',
      options: JSON.stringify(['Jean-Jacques Dessalines', 'Toussaint Louverture', 'Henri Christophe', 'Alexandre Pétion']),
      correctAnswer: 'Jean-Jacques Dessalines',
      solution: 'Jean-Jacques Dessalines est considéré comme le père de la nation haïtienne. Il a proclamé l\'indépendance le 1er janvier 1804.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Histoire d\'Haïti',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quel est le nom du dirigeant français qui a envoyé l\'expédition pour reprendre Haïti en 1802 ?',
      options: JSON.stringify(['Napoléon Bonaparte', 'Louis XVI', 'Charles de Gaulle', 'Jacques Chirac']),
      correctAnswer: 'Napoléon Bonaparte',
      solution: 'Napoléon Bonaparte a envoyé le général Charles Leclerc à la tête d\'une expédition de plus de 20 000 soldats en 1802.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Histoire d\'Haïti',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'La Citadelle Laferrière a été construite sous le règne de quel empereur haïtien ?',
      options: JSON.stringify(['Henri Christophe', 'Jean-Jacques Dessalines', 'Faustin Soulouque', 'Alexandre Pétion']),
      correctAnswer: 'Henri Christophe',
      solution: 'La Citadelle Laferrière a été construite entre 1805 et 1820 sous le règne du roi Henri Christophe. Classée au patrimoine mondial de l\'UNESCO depuis 1982.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Histoire d\'Haïti',
      difficulty: 'DIFFICILE',
      questionType: 'QCM',
      question: 'Quel événement a marqué le début de la Révolution haïtienne en 1791 ?',
      options: JSON.stringify([
        'La cérémonie du Bois Caïman',
        'La prise de la Bastille',
        'Le serment de Pétion',
        'La bataille de Vertières',
      ]),
      correctAnswer: 'La cérémonie du Bois Caïman',
      solution: 'La cérémonie du Bois Caïman, en août 1791, est considérée comme l\'événement déclencheur de la Révolution haïtienne.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Géographie',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quelle est la capitale d\'Haïti ?',
      options: JSON.stringify(['Port-au-Prince', 'Cap-Haïtien', 'Les Cayes', 'Jérémie']),
      correctAnswer: 'Port-au-Prince',
      solution: 'Port-au-Prince est la capitale et la plus grande ville d\'Haïti, fondée en 1749.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Géographie',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quel est le plus haut sommet d\'Haïti ?',
      options: JSON.stringify(['Pic la Selle', 'Pic Macaya', 'Montagne Noire', 'Morne de la Selle']),
      correctAnswer: 'Pic la Selle',
      solution: 'Le Pic la Selle, dans le massif de la Selle, est le point culminant d\'Haïti avec 2 680 mètres.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Culture générale',
      difficulty: 'FACILE',
      questionType: 'QCM',
      question: 'Quelles sont les deux langues officielles d\'Haïti ?',
      options: JSON.stringify(['Le français et le créole haïtien', 'L\'espagnol et le français', 'L\'anglais et le créole', 'Le français et l\'anglais']),
      correctAnswer: 'Le français et le créole haïtien',
      solution: 'Haïti a deux langues officielles : le français et le créole haïtien (kreyòl ayisyen).',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Culture générale',
      difficulty: 'MOYEN',
      questionType: 'QCM',
      question: 'Quel organisme international Haïti a-t-elle rejoint en 1945, année de sa fondation ?',
      options: JSON.stringify(['L\'ONU', 'L\'Union européenne', 'L\'OTAN', 'L\'UNESCO']),
      correctAnswer: 'L\'ONU',
      solution: 'Haïti est l\'un des pays fondateurs de l\'Organisation des Nations Unies (ONU), qu\'elle a rejointe en 1945.',
      points: 4,
    },
    {
      subject: 'CULTURE_GENERALE',
      topic: 'Culture générale',
      difficulty: 'DIFFICILE',
      questionType: 'QCM',
      question: 'Quel auteur haïtien est célèbre pour son roman "Gouverneurs de la rosée" ?',
      options: JSON.stringify(['Jacques Roumain', 'René Depestre', 'Jean Price-Mars', 'Frankétienne']),
      correctAnswer: 'Jacques Roumain',
      solution: 'Jacques Roumain (1907-1944) est l\'auteur de "Gouverneurs de la rosée" (1944), chef-d\'oeuvre de la littérature caribéenne.',
      points: 4,
    },
  ];

export async function POST() {
  try {
    // Check if already seeded
    const existingCount = await db.exercise.count();
    if (existingCount > 0) {
      return NextResponse.json({
        success: true,
        message: `Base de données déjà initialisée avec ${existingCount} exercices.`,
        exerciseCount: existingCount,
      });
    }

    // Create default student
    await db.student.create({ data: { name: 'Étudiant' } });

    // Seed exercises in batches
    const BATCH_SIZE = 20;
    for (let i = 0; i < EXERCISES.length; i += BATCH_SIZE) {
      const batch = EXERCISES.slice(i, i + BATCH_SIZE);
      await db.exercise.createMany({ data: batch });
    }

    return NextResponse.json({
      success: true,
      message: `Base de données initialisée avec succès ! ${EXERCISES.length} exercices créés.`,
      exerciseCount: EXERCISES.length,
    });
  } catch (error) {
    console.error('Setup error:', error);
    return NextResponse.json(
      { success: false, error: 'Erreur lors de l\'initialisation : ' + String(error) },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const exerciseCount = await db.exercise.count();
    const studentCount = await db.student.count();
    const isSeeded = exerciseCount > 0;

    return NextResponse.json({
      isSeeded,
      exerciseCount,
      studentCount,
      message: isSeeded
        ? `Base de données prête (${exerciseCount} exercices)`
        : 'Base de données non initialisée. Appelez POST /api/setup pour initialiser.',
    });
  } catch (error) {
    return NextResponse.json(
      { isSeeded: false, error: String(error) },
      { status: 500 }
    );
  }
}
